import type { Metadata, Viewport } from "next";
import "./globals.css";
import RegisterSW from "@/components/RegisterSW";

export const metadata: Metadata = {
  title: "Cromos 2026",
  description: "Intercambiá figuritas del Mundial 2026 con tus amigos",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Cromos 2026",
  },
  icons: {
    apple: "/icons/apple-touch-icon.png",
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    other: [
      // Apple-touch-startup-image splash screens — one per iPhone resolution tier.
      // Images generated by scripts/generate-splash.mjs; update paths if you add
      // more sizes. Andy: swap placeholder PNGs with real screenshots once captured.
      {
        rel: "apple-touch-startup-image",
        url: "/splash/iphone-640x1136.png",
        // iPhone SE (1st gen) — 320×568 @2x
        media:
          "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        url: "/splash/iphone-750x1334.png",
        // iPhone 8, SE 2nd/3rd gen — 375×667 @2x
        media:
          "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        url: "/splash/iphone-1179x2556.png",
        // iPhone 14 Pro, 15, 16 — 393×852 @3x
        media:
          "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        url: "/splash/iphone-1170x2532.png",
        // iPhone 14 — 390×844 @3x
        media:
          "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        url: "/splash/iphone-1284x2778.png",
        // iPhone 14 Plus, 15 Plus, 16 Plus — 428×926 @3x
        media:
          "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        url: "/splash/iphone-1290x2796.png",
        // iPhone 14 Pro Max, 15 Pro Max, 16 Pro Max — 430×932 @3x
        media:
          "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)",
      },
    ],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // a11y: allow up to 2× pinch zoom (Lighthouse requirement — removes [user-scalable="no"] penalty)
  // iOS input-zoom prevention is now handled by font-size: 16px on inputs (correct fix),
  // not by blocking zoom entirely.
  maximumScale: 2,
  userScalable: true,
  viewportFit: "cover", // enable safe-area-inset support on notched phones
  themeColor: "#006847",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {children}
        <RegisterSW />
      </body>
    </html>
  );
}
